apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  #  namespace: amit
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      initContainers:
        - name: init-opentelemetry
          image: curlimages/curl:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - curl -L -o /app/libs/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.0/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /app/libs
      containers:
        - name: configserver
          image: justamitsaha/ms-config-server:observability
          ports:
            - containerPort: 8071
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: JAVA_OPTS
              value: "-Duser.timezone=Asia/Kolkata"
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_PASSWORD
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: JAVA_TOOL_OPTIONS
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: OTEL_METRICS_EXPORTER
            - name: OTEL_SERVICE_NAME
              value: config-server
          volumeMounts:
            - name: otel-agent
              mountPath: /app/libs   # open telemetry  will be loaded at this path by init container
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8071
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8071
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8071
            initialDelaySeconds: 60
            periodSeconds: 15

      volumes:
        - name: otel-agent
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: configserver
#  namespace: amit
spec:
  selector:
    app: configserver
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
