apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
#  namespace: amit
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: wait-for-identity-service
          image: appropriate/curl:latest
          command:
            - /bin/sh
            - -c
            - >
              until curl --fail --silent http://gateway-service:8080/authentication/user/findById/1 | grep 'Amit'; do
                echo "Waiting for identity-service to be UP";
                sleep 20;
              done;
        - name: init-opentelemetry
          image: curlimages/curl:latest
          command: [ "/bin/sh", "-c" ]
          args:
            - curl -L -o /app/libs/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.0/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /app/libs
      containers:
        - name: product-service
          image: justamitsaha/ms-product-service:observability
          ports:
            - containerPort: 8091
          volumeMounts:
            - name: otel-agent
              mountPath: /app/libs   # open telemetry  will be loaded at this path by init container
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: EUREKA_HOST
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: CONFIG_SERVER_URI
            - name: TZ
              value: "Asia/Kolkata"
            - name: JAVA_OPTS
              value: "-Duser.timezone=Asia/Kolkata"
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: JAVA_TOOL_OPTIONS
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: OTEL_METRICS_EXPORTER
            - name: OTEL_SERVICE_NAME
              value: product-service

          startupProbe:
            httpGet:
              path: /product/actuator/health
              port: 8091
            initialDelaySeconds: 60 # Wait 60 seconds before first check
            periodSeconds: 10 # Check every 10 seconds
            failureThreshold: 10 # Fail after 10 unsuccessful checks

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  curl --fail --silent http://localhost:8091/product/findById/100 | grep productDescription || exit 1
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /product/actuator/health
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: otel-agent
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
#  namespace: amit
spec:
  selector:
    app: product-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
