apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: amit
data:
  grafana.ini: |
    [server]
    root_url = http://34.71.117.30:32000/grafana/
    serve_from_sub_path = true

