apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: amit
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'identity-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'identity-service:8090' ]
      - job_name: 'product-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'product-service:8091' ]
      - job_name: 'gateway-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'gateway-service:8080' ]
      - job_name: 'discovery-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'discovery-service:8081' ]
      - job_name: 'configserver'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'configserver:8071' ]
