apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy
  namespace: amit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:v1.0.0
          args:
            - run
            - --server.http.listen-addr=0.0.0.0:12345
            - --storage.path=/var/lib/alloy/data
            - /etc/alloy/config.alloy
          ports:
            - containerPort: 12345
          volumeMounts:
            - name: config
              mountPath: /etc/alloy/config.alloy
              subPath: alloy-local-config.yaml  # Corrected with subPath
      volumes:
        - name: config
          configMap:
            name: alloy-config
