apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: amit
spec:
  type: NodePort
  ports:
    - port: 80          # External Port
      targetPort: 3000  # Grafana Internal Port
      nodePort: 32000   # Choose port between 30000-32767
  selector:
    app: grafana