apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: amit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-05-27T19-17-46Z
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
          env:
            - name: MINIO_ROOT_USER
              value: loki
            - name: MINIO_ROOT_PASSWORD
              value: supersecret
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
