apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: amit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.4.2
          args:
            - -config.file=/etc/tempo/tempo.yml  # Corrected path and file name
          ports:
            - name: http
              containerPort: 3100
            - name: grpc
              containerPort: 4317
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
