apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
  namespace: amit
  labels:
    app: identity-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      initContainers:
        - name: wait-for-discovery-service
          image: appropriate/curl:latest
          command:
            - /bin/sh
            - -c
            - >
              until curl --fail --silent http://discovery-service:8081/discovery/actuator/health | grep '"status":"UP"'; do
                echo "Waiting for discovery-service to be UP";
                sleep 5;
              done
      containers:
        - name: identity-service
          image: justamitsaha/ms-identity-service:config_bus_update
          ports:
            - containerPort: 8090
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: EUREKA_HOST
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: CONFIG_SERVER_URI
            - name: TZ
              value: "Asia/Kolkata"
            - name: JAVA_OPTS
              value: "-Duser.timezone=Asia/Kolkata"
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: microservice-master-configmap
                  key: RABBITMQ_PASSWORD
#          startupProbe:
#            httpGet:
#              path: /identity/actuator/health
#              port: 8090
#            initialDelaySeconds: 30 # Wait 10 seconds before first check
#            periodSeconds: 5 # Check every 5 seconds
#            failureThreshold: 6 # Fail after 6 unsuccessful checks
#
#          livenessProbe:
#            exec:
#              command:
#                - /bin/sh
#                - -c
#                - >
#                  curl --fail --silent http://localhost:8090/identity/user/findById/1 | grep Amit || exit 1
#            initialDelaySeconds: 30
#            periodSeconds: 10
#
#          readinessProbe:
#            httpGet:
#              path: /identity/actuator/health
#              port: 8090
#            initialDelaySeconds: 30
#            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service # other pods in the cluster will identify this one with this field
  namespace: amit
spec:
  selector:
    app: identity-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
