apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
  labels:
    app: identity-service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: justamitsaha/ms-identity-service:2Kube
          ports:
            - containerPort: 8090
          env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: microservice-master-configmap
                key: EUREKA_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090