apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-master-configmap
  namespace: amit # Assigning to namespace 'amit'
data:
  KEYCLOAK_ADMIN_USERNAME: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  EUREKA_HOST: "http://discovery-service:8081/discovery/eureka/"
  CONFIG_SERVER_URI: "optional:configserver:http://me.amit.com/config/"